---
os:
  - ubuntu
dist: trusty

language: python

# Use the new container infrastructure
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update
  - sudo apt-get install ansible

script:
  # Basic role syntax check
  - ansible-playbook -i localhost provision.yml --syntax-check
  - ansible-playbook -i localhost provision.yml --list-tasks --list-hosts
