---
os:
  - ubuntu
dist: trusty

# Use the new container infrastructure
#sudo: false

before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install ansible

script:
  # Basic role syntax check
  - ansible-playbook -i localhost provision.yml --syntax-check
