---
os:
  - ubuntu
dist: trusty

language: python

# Use the new container infrastructure
sudo: required

before_install:
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update
  - sudo apt-get install ansible
  - sudo service postgresql stop

stages:
  - smoketest

jobs:
  include:
    - stage: smoketest
      script:
        - ansible-playbook -i localhost provision.yml --syntax-check
        # - ansible-playbook -i ci provision.yml --tags common
