---
# tasks file for gnome

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  when: lookup('env','TRAVIS') != 'true'

- name: Add gnome repo
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - 'ppa:snwh/pulp'

- name: Install gnome
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - paper-icon-theme
  - paper-cursor-theme

- name: Download Materia
  unarchive:
    src: https://github.com/nana-4/materia-theme/archive/v20180321.zip
    dest: /tmp
    copy: no

- name: Install flatplat
  shell: ./install.sh
  args:
    chdir: /tmp/materia-theme-20180321

- name: Install extensions
  gnome_shell_extension:
    id: "{{ item.id }}"
    gnome_extension_path: "{{ item.path }}"
  with_items:
  - { id: '1160', path: "/home/{{ ansible_user }}/.local/share/gnome-shell/extensions/" }
  - { id: '800', path: "/home/{{ ansible_user }}/.local/share/gnome-shell/extensions/" }
  - { id: '1031', path: "/home/{{ ansible_user }}/.local/share/gnome-shell/extensions/" }
  - { id: '19', path: "/home/{{ ansible_user }}/.local/share/gnome-shell/extensions/" }

- name: Correct permissions
  file:
    name: "/home/{{ ansible_user }}/.local"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: yes

- name: Download assets
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  with_items:
  - {url: 'https://d3vv6lp55qjaqc.cloudfront.net/items/113T0b0f1Z302a1V3G3S/5120x2880.png', dest: "/home/{{ ansible_user }}/mountain-minimalist.png"}

- name: Unzip fonts
  unarchive:
    src: 'https://github.com/RedHatBrand/Overpass/releases/download/3.0.2/overpass-desktop-fonts.zip'
    dest: /usr/share/fonts
    copy: no

- name: Configure theme
  gsettings:
    user: "{{ ansible_user }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - { key: org.gnome.desktop.interface.gtk-theme, value: "'Flat-Plat'" }
  - { key: org.gnome.desktop.interface.icon-theme, value: "'Paper'" }
  - { key: org.gnome.desktop.interface.cursor-theme, value: "'Paper'" }
  - { key: org.gnome.desktop.interface.gtk-key-theme, value: "'Flat-Plat'" }
  - { key: org.gnome.desktop.interface.monospace-font-name, value: "'Overpass Mono 11'" }
  - { key: org.gnome.desktop.interface.font-name, value: "'Overpass 11'" }
  - { key: org.gnome.desktop.interface.document-font-name, value: "'Overpass 11'" }
  - { key: org.gnome.shell.extensions.user-theme.name, value: "'Flat-Plat'" }
  - { key: org.gnome.desktop.wm.preferences.theme, value: "'Flat-Plat'" }
  - { key: org.gnome.desktop.wm.preferences.titlebar-font, value: "'Overpass Bold 11'" }
  - { key: org.gnome.desktop.background.picture-uri, value: "file:///home/{{ ansible_user }}/mountain-minimalist.png" }
  - { key: org.gnome.shell.enabled-extensions, value: "['dash-to-panel@jderose9.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'TopIcons@phocean.net', 'remove-dropdown-arrows@mpdeimos.com']" }

- name: Copy lockscreen config
  copy:
    src: /usr/share/themes/Materia/gnome-shell/gnome-shell-theme.gresource.xml
    dest: /usr/share/gnome-shell/gnome-shell-theme.gresource
    owner: root
    group: root
    mode: '0644'
    remote_src: true
    backup: true

- name: Copy gnome terminal config
  copy:
    src: glacier.sh
    dest: "/home/{{ ansible_user }}/glacier.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
