---
# tasks file for common

- name: Remove amazon shortcut
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
   - ubuntu-web-launchers
   - aisleriot
   - gnome-mahjongg
   - gnome-mines
   - gnome-sudoku

- name: Create spotify shortcut folder
  file:
    path: /usr/share/desktop-directories
    state: directory
    owner: root
    group: root

- name: Install chrome + atom keys
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items:
    - { url: "https://dl-ssl.google.com/linux/linux_signing_key.pub", state: present }
    - { url: "https://packagecloud.io/AtomEditor/atom/gpgkey", state: present }

- name: Install spotify key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: '931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90'

- name: Install repos
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.filename }}"
  with_items:
  - {repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main', filename: 'google-chrome'}
  - {repo: 'deb http://repository.spotify.com stable non-free', filename: 'spotify' }
  - {repo: 'deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main', filename: 'atom' }

- name: Install common binaries
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - vim
  - vpnc
  - network-manager-vpnc-gnome
  - zeal
  - google-chrome-stable
  - spotify-client
  - wget
  - htop
  - python-pip
  - screenfetch
  - ansible
  - atom
  - gconf-editor
  - gnome-terminal

- name: Install web binaries
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
  - 'https://downloads.slack-edge.com/linux_releases/slack-desktop-3.1.1-amd64.deb'
  - 'https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb'
  - 'https://github.com/zeit/hyper/releases/download/2.0.0/hyper_2.0.0_amd64.deb'

- name: Copy hyper config
  copy:
    src: .hyper.js
    dest: "/home/{{ ansible_user }}/.hyper.js"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0664'

- block:
    - name: Install atom packages
      shell: apm install sync-settings@0.8.6
  rescue:
    - name: apm not availible
      debug:
        msg: "There was an error accessing apm"
