---
# tasks file for common

- name: Create bash aliases
  template:
    src: bash_profile.j2
    dest: "{{ ansible_user_dir }}/.bash_profile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Create development folder
  file:
    path: "{{ ansible_user_dir }}/development"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create spotify shortcut folder
  file:
    path: /usr/share/desktop-directories
    state: directory
    owner: root
    group: root

- name: Install apt keys
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items:
    - { url: "https://dl-ssl.google.com/linux/linux_signing_key.pub", state: present }
    - { url: "https://packagecloud.io/AtomEditor/atom/gpgkey", state: present }
    - { url: "https://download.docker.com/linux/ubuntu/gpg ", state: present }

- name: Install spotify key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: '931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90'

- name: Install repos
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.filename }}"
  with_items:
  - {repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main', filename: 'google-chrome'}
  - {repo: 'deb http://repository.spotify.com stable non-free', filename: 'spotify' }
  - {repo: 'deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main', filename: 'atom' }
  - {repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable main", filename: 'docker' }

- name: Install common binaries
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - vim
  - vpnc
  - network-manager-vpnc-gnome
  - openconnect
  - network-manager-openconnect-gnome
  - zeal
  - google-chrome-stable
  - spotify-client
  - wget
  - htop
  - python-pip
  - screenfetch
  - ansible
  - atom
  - gconf-editor
  - gnome-terminal
  - docker-ce

- name: Install web debs
  apt:
    deb: "{{ item }}"
    state: present
  with_items:
  - 'https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.8-amd64.deb'
  - 'https://github.com/zeit/hyper/releases/download/2.1.2/hyper_2.1.2_amd64.deb'
  - 'https://github.com/shiftkey/desktop/releases/download/release-1.6.5-linux6/GitHubDesktop-linux-1.6.5-linux6.deb'

- name: Install web binaries
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: add  user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Copy hyper config
  copy:
    src: .hyper.js
    dest: "/home/{{ ansible_user }}/.hyper.js"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0664'

- block:
    - name: Install atom sync package
      shell: apm install sync-settings@0.8.6
      become: yes
      become: "{{ ansible_user }}"
  rescue:
    - name: apm not availible
      debug:
        msg: "There was an error accessing apm"

- name: Set systemd to use windows time settings (dual boot)
  shell: timedatectl set-local-rtc 1 --adjust-system-clock
