name: Main workflow
on: [push]
jobs:
  macOS:
    name: ubuntu integration
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: setup ruby env
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: lint yaml set
        run: |
          gem install yaml-lint
          yaml-lint -i $GITHUB_WORKSPACE

      - name: install ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible -y
          sudo apt-get update
          sudo apt-get install ansible

      - name: run bootstrap playbook
        run: |
          ansible-playbook -i localhost provision.yml --syntax-check
          ansible-playbook -i actions provision.yml -t common,nvidia,awscli
